@startuml

package "ua.kiev.prog.summaryTask" {
!include Answers.puml
!include IAnswer.puml
!include ITeach.puml
!include Journal.puml
!include Mark.puml
!include Marks.puml
!include NamedPerson.puml
!include Parent.puml
!include Pupil.puml
!include Task.puml
!include TaskList.puml
!include TaskWithAnswer.puml
!include Teacher.puml
}
@enduml