@startuml
class NamedPerson {
    private String name = null;
    private String surname = null;

    public NamedPerson(String name, String surname)

    public String getName()

    public String getSurname()

    public String toString()
}
@enduml