@startuml
!include NamedPerson.puml
!include IAnswer.puml
class Pupil extends NamedPerson implements IAnswer {
    private NamedPerson mother;
    private NamedPerson father;

    public Pupil(String name, String surname, NamedPerson mother, NamedPerson father)

    public NamedPerson getMother()

    public NamedPerson getFather()

    public String getAnswer(Task task)
}
@enduml