@startuml
class Task {
    private static int counter = 0;
    private final int id = counter++;
    private final String text;

    public Task(String text)

    public int getId()

    public String getText()

    public String toString()
}
@enduml