@startuml
!include Task.puml
class TaskList implements Iterable {
    private List<Task> tasks = new ArrayList<Task>();

    public TaskList add(Task... task)

    public TaskList remove(Task task)
    List<Task> getAll()

    public String toString()
    public Iterator<Task> iterator()
}
@enduml